version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGREST_USER=postgres
      - POSTGRES_PASSWORD=mmmdg4530
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data