# Generated by Django 4.1.4 on 2022-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(blank=True, to='app.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='part',
            field=models.ManyToManyField(blank=True, to='app.lessonpart'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task',
            field=models.ManyToManyField(blank=True, to='app.task'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='courses',
            field=models.ManyToManyField(blank=True, to='app.course'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
