# Generated by Django 4.1.4 on 2022-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_speciality_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='members',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
