# Generated by Django 4.1.4 on 2023-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_members_alter_module_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='app.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task',
            field=models.ManyToManyField(to='app.task'),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='module',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
