# Generated by Django 4.1.4 on 2023-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(blank=True, upload_to='app/lesson/presentation_file/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='support_downloads',
            field=models.FileField(blank=True, upload_to='app/lesson/support_downloads/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task',
            field=models.ManyToManyField(blank=True, to='app.task'),
        ),
    ]
