# Generated by Django 4.1.4 on 2023-02-02 16:52

import app.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_lesson_presentation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(blank=True, upload_to=app.helpers.SaveImages.presentation_file_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='support_downloads',
            field=models.FileField(blank=True, upload_to=app.helpers.SaveImages.support_downloads_path),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='video',
            field=models.FileField(upload_to=app.helpers.SaveImages.video_gallery_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to=app.helpers.SaveImages.teacher_images_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_company_logo',
            field=models.ImageField(upload_to=app.helpers.SaveImages.work_company_logo),
        ),
    ]
