# Generated by Django 4.1.4 on 2023-02-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_lesson_presentation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
